# Generated by Django 2.2.6 on 2019-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='month',
            field=models.TextField(),
        ),
    ]
